"""Generate / check the OKF `index.md` files of docs/ from concept frontmatter.

    python -m mimir_decide.okf --write     # regenerate every index.md under docs/
    python -m mimir_decide.okf --check     # exit 1 if any index is stale or an OKF rule is broken (used by tests)

OKF rules enforced (https://okf.md/spec): every non-reserved .md has YAML frontmatter with a non-empty `type`;
index.md has no frontmatter and lists every concept of its folder as `* [Title](/abs/path.md) - description`;
log.md (reserved) has ISO date headings, newest first. We additionally require that absolute links resolve.
Concept pages may carry extra frontmatter (status, date, ...); `status` is shown in the index entry.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

DOCS = Path(__file__).resolve().parents[1] / "docs"
RESERVED = {"index.md", "log.md"}

# folder -> (heading, intro). Order here is the order in the root index.
FOLDERS = {
    "research": ("Research", "What is known about decision models, Jev, Mimir and HRM-Text, with sources."),
    "design": ("Design", "Decision records (one page per decision, with context and consequences) and how-to references."),
    "questions": ("Open questions", "One page per open question: why it matters, how to resolve it, linked experiments."),
    "experiments": ("Experiments", "Prefilled experiment plans: hypothesis, exact commands, metrics, decision rule, results."),
    "observations": ("Observations", "Dated, evidence-backed things seen so far; add new ones with the template."),
}
ROOT_TITLE = "Mimir-Decide knowledge base"
ROOT_INTRO = ("Turning DFM Mimir (HRM-Text) into a Jev-like decision model. Managed as an Open Knowledge Format bundle: "
              "every page has frontmatter with a `type`, indexes are generated by `python -m mimir_decide.okf --write`, "
              "and every decision, finding or result is also recorded in the [update log](/log.md). "
              "Agents: read `AGENTS.md` in the repository root first.")


def frontmatter(p: Path) -> dict | None:
    m = re.match(r"^---\n(.*?)\n---\n", p.read_text(), re.S)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:  # reported by problems(); never crash the generator on one bad page
        return {"__error__": str(e).splitlines()[0]}


def concept_files(folder: Path) -> list[Path]:
    return sorted(p for p in folder.glob("*.md") if p.name not in RESERVED)


def entry(p: Path, docs: Path) -> str:
    fm = frontmatter(p) or {}
    status = f"[{fm['status']}] " if fm.get("status") else ""
    return f"* [{fm.get('title', p.stem)}](/{p.relative_to(docs)}) - {status}{fm.get('description', '')}"


def render_folder_index(folder: Path, docs: Path) -> str:
    title, intro = FOLDERS[folder.name]
    groups: dict[str, list[Path]] = {}
    for p in concept_files(folder):
        groups.setdefault(str((frontmatter(p) or {}).get("type", "Other")), []).append(p)
    out = [f"# {title}", "", intro, ""]
    for t in sorted(groups, key=lambda x: (x == "Template", x)):
        out += [f"## {t}", ""] + [entry(p, docs) for p in groups[t]] + [""]
    return "\n".join(out).rstrip() + "\n"


def render_root_index(docs: Path) -> str:
    out = [f"# {ROOT_TITLE}", "", ROOT_INTRO, "", "## Sections", ""]
    for name, (title, intro) in FOLDERS.items():
        n = len(concept_files(docs / name))
        out.append(f"* [{title}](/{name}/index.md) - {intro} ({n} pages)")
    out += ["", "## Log", "", "* [Update log](/log.md) - Dated record of decisions, findings, fixes and verification", ""]
    return "\n".join(out)


def expected_indexes(docs: Path) -> dict[Path, str]:
    res = {docs / "index.md": render_root_index(docs)}
    for name in FOLDERS:
        res[docs / name / "index.md"] = render_folder_index(docs / name, docs)
    return res


def problems(docs: Path = DOCS) -> list[str]:
    out = []
    for p in docs.rglob("*.md"):
        if p.name in RESERVED:
            continue
        fm = frontmatter(p)
        if fm and "__error__" in fm:
            out.append(f"{p.relative_to(docs)}: invalid YAML frontmatter ({fm['__error__']})")
        elif not fm or not str(fm.get("type", "")).strip():
            out.append(f"{p.relative_to(docs)}: missing frontmatter or empty type")
    for p, text in expected_indexes(docs).items():
        if not p.exists() or p.read_text() != text:
            out.append(f"{p.relative_to(docs)}: index is stale (run `python -m mimir_decide.okf --write`)")
        elif p.read_text().startswith("---"):
            out.append(f"{p.relative_to(docs)}: index.md must not have frontmatter")
    for p in docs.rglob("*.md"):
        for m in re.finditer(r"\]\((/[^)\s#]+)\)", p.read_text()):
            if not (docs / m.group(1).lstrip("/")).exists():
                out.append(f"{p.relative_to(docs)}: broken link {m.group(1)}")
    log = docs / "log.md"
    if log.exists():
        dates = re.findall(r"^## (\S+)$", log.read_text(), re.M)
        if not all(re.fullmatch(r"\d{4}-\d{2}-\d{2}", d) for d in dates) or dates != sorted(dates, reverse=True):
            out.append("log.md: date headings must be ISO and newest first")
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    ap.add_argument("--docs", default=str(DOCS))
    a = ap.parse_args(argv)
    docs = Path(a.docs)
    if a.write:
        for p, text in expected_indexes(docs).items():
            p.write_text(text)
        print(f"wrote {len(expected_indexes(docs))} index files")
    bad = problems(docs)
    for b in bad:
        print("PROBLEM:", b)
    if a.check or bad:
        sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
